[package]
name = "caravela"
authors = ["António Leitão"]
version = "0.1.0"
description = "Native Rust implementation of efficient basic linear algebra routines"
repository = "https://github.com/antonio-leitao/caravela"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
num-traits = "0.2.19"

[dev-dependencies]
criterion = "0.5"
rand = "0.8"
approx = "0.5"

[[bench]]
name = "dot"
harness = false


[[bench]]
name = "gemv"
harness = false

[[bench]]
name = "gemm"
harness = false

